site_name: DocScanner – RAG based AI Review tool
theme:
  name: material   # or your org theme

nav:
  - Home: index.md
  - Features: features.md
  - Technology: technology.md
  - Usage Guide: usage.md
  - Installation: how-to-use.md
  - FAQ: faq.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
